on: [ push ]

jobs:
  hello_world_job:
    name: Um novo job
    runs-on: ubuntu-lastet
    steps:
      - uses: actions/checkout@v4
      - name: Hello World
        id: hello-world
        uses: LuizAntonioConstante/modulos-git@v1
        with:
          my-input: world
